# Generated by Django 5.2.12 on 2026-04-11 04:56
# This migration has been corrected to avoid conflicts with existing fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_update_daily_challenge_xp_rewards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchallengeprogress',
            options={'ordering': ['-challenge__date']},
        ),
        # Only perform field operations if the fields exist in the expected state
        # Skip rename operations since the model already has the correct field names
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        # Update challenge_type choices to the correct values
        migrations.AlterField(
            model_name='dailychallenge',
            name='challenge_type',
            field=models.CharField(
                choices=[
                    ('exam', 'Complete an exam'), 
                    ('flashcard', 'Study flashcards'), 
                    ('streak', 'Maintain login streak'), 
                    ('score', 'Achieve minimum score'), 
                    ('questions', 'Answer questions correctly')
                ], 
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='target_value',
            field=models.IntegerField(help_text='Target to complete (e.g., 10 flashcards, 80% score)'),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='xp_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userchallengeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
