# Generated by Django 5.2.12 on 2026-04-11 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_update_daily_challenge_xp_rewards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchallengeprogress',
            options={'ordering': ['-challenge__date']},
        ),
        migrations.RenameField(
            model_name='userchallengeprogress',
            old_name='completed_date',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='userchallengeprogress',
            old_name='current_progress',
            new_name='current_value',
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddField(
            model_name='userchallengeprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='challenge_type',
            field=models.CharField(choices=[('exam', 'Complete an exam'), ('flashcard', 'Study flashcards'), ('streak', 'Maintain login streak'), ('score', 'Achieve minimum score'), ('questions', 'Answer questions correctly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='target_value',
            field=models.IntegerField(help_text='Target to complete (e.g., 10 flashcards, 80% score)'),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='xp_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userchallengeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userchallengeprogress',
            name='start_date',
        ),
    ]
