# Generated by Django 5.2.13 on 2026-04-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_userchallengeprogress_options_and_more'),
    ]

    operations = [
    ]
