# Generated by Django 5.2.12 on 2026-04-08 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kien_thuc', '0008_baiviet_moderated_at_baiviet_moderated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('top_10_daily', 'Top 10 Hàng ngày'), ('top_10_weekly', 'Top 10 Hàng tuần'), ('top_10_monthly', 'Top 10 Hàng tháng'), ('top_100_all_time', 'Top 100 Mọi thời gian'), ('subject_master', 'Bậc thầy môn học'), ('flashcard_king', 'Vua Flashcard'), ('exam_champion', 'Nhà vô địch Đề thi')], max_length=30)),
                ('rank_achieved', models.IntegerField(blank=True, null=True)),
                ('score_achieved', models.FloatField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('mon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kien_thuc.mon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thành tựu',
                'verbose_name_plural': 'Thành tựu',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('all_time', 'Mọi thời gian')], max_length=20)),
                ('category', models.CharField(choices=[('overall', 'Tổng thể'), ('subject', 'Theo môn'), ('flashcard', 'Flashcard'), ('exam', 'Đề thi')], max_length=20)),
                ('rankings', models.JSONField(default=list, help_text='[{user_id, username, score, rank}, ...]')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mon', models.ForeignKey(blank=True, help_text='Chỉ dùng khi category=subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='kien_thuc.mon')),
            ],
            options={
                'verbose_name': 'Bảng xếp hạng',
                'verbose_name_plural': 'Bảng xếp hạng',
                'ordering': ['period', 'category'],
                'unique_together': {('period', 'category', 'mon')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('exams_completed', models.IntegerField(default=0)),
                ('flashcards_learned', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboard.leaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry xếp hạng',
                'verbose_name_plural': 'Entry xếp hạng',
                'ordering': ['rank'],
                'unique_together': {('user', 'leaderboard')},
            },
        ),
    ]
