# Generated by Django 5.2.12 on 2026-04-08 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0008_baiviet_moderated_at_baiviet_moderated_by_and_more'),
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'achievement_type'], name='leaderboard_user_id_a93277_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['earned_at'], name='leaderboard_earned__198787_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['period', 'category'], name='leaderboard_period_a273e4_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['last_updated'], name='leaderboard_last_up_1af4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['leaderboard', 'rank'], name='leaderboard_leaderb_465d92_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['user', 'leaderboard'], name='leaderboard_user_id_84426a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['score'], name='leaderboard_score_9878b5_idx'),
        ),
    ]
