# Generated by Django 5.2.12 on 2026-04-11 05:29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_leaderboardentry_flashcard_avg_score_and_more'),
    ]

    operations = [
        # Add the total_score field which is causing the error
        migrations.AddField(
            model_name='leaderboardentry',
            name='total_score',
            field=models.FloatField(db_index=True, help_text='Total accumulated score', default=0),
        ),
    ]
