# Generated by Django 5.2.13 on 2026-04-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_auto_20260411_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='total_study_time_minutes',
            field=models.IntegerField(default=0, help_text='Total study time in minutes (exams + flashcards)'),
        ),
    ]
