# Generated by Django 5.2.12 on 2026-04-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguoi_dung', '0003_usergamification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usergamification',
            new_name='nguoi_dung__xp_876be4_idx',
            old_name='nguoi_dung_xp_idx',
        ),
        migrations.RenameIndex(
            model_name='usergamification',
            new_name='nguoi_dung__level_635834_idx',
            old_name='nguoi_dung_level_idx',
        ),
        migrations.RenameIndex(
            model_name='usergamification',
            new_name='nguoi_dung__current_9abf17_idx',
            old_name='nguoi_dung_streak_idx',
        ),
    ]
