# Generated by Django 5.2.12 on 2026-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoi_dung', '0004_rename_nguoi_dung_xp_idx_nguoi_dung__xp_876be4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng')], max_length=10),
        ),
    ]
