# Generated by Django 5.2.12 on 2026-04-06 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mon', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('thoi_gian_phut', models.IntegerField(default=50)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('an', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Đề thi',
                'verbose_name_plural': 'Đề thi',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('tn', 'Trắc nghiệm ABCD'), ('ds', 'Trắc nghiệm Đúng/Sai'), ('dien', 'Điền số')], default='tn', max_length=10)),
                ('noi_dung', models.TextField()),
                ('giai_thich', models.TextField(blank=True)),
                ('thu_tu', models.IntegerField(default=0)),
                ('dap_an_a', models.CharField(blank=True, max_length=500)),
                ('dap_an_b', models.CharField(blank=True, max_length=500)),
                ('dap_an_c', models.CharField(blank=True, max_length=500)),
                ('dap_an_d', models.CharField(blank=True, max_length=500)),
                ('dap_an_dung', models.CharField(blank=True, max_length=10)),
                ('y_a', models.CharField(blank=True, max_length=500)),
                ('y_b', models.CharField(blank=True, max_length=500)),
                ('y_c', models.CharField(blank=True, max_length=500)),
                ('y_d', models.CharField(blank=True, max_length=500)),
                ('dung_sai_a', models.BooleanField(default=False)),
                ('dung_sai_b', models.BooleanField(default=False)),
                ('dung_sai_c', models.BooleanField(default=False)),
                ('dung_sai_d', models.BooleanField(default=False)),
                ('dap_an_so', models.CharField(blank=True, max_length=100)),
                ('de_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi', to='de_thi.dethi')),
            ],
            options={
                'ordering': ['thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='KetQua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.FloatField(default=0)),
                ('tong_cau', models.IntegerField(default=0)),
                ('thoi_gian_lam', models.IntegerField(default=0)),
                ('che_do', models.CharField(default='luyen_tap', max_length=20)),
                ('ngay_lam', models.DateTimeField(auto_now_add=True)),
                ('da_xem_dap_an', models.BooleanField(default=False)),
                ('de_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='de_thi.dethi')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_lam'],
            },
        ),
        migrations.CreateModel(
            name='TraLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chon', models.CharField(blank=True, max_length=10)),
                ('chon_a', models.BooleanField(blank=True, null=True)),
                ('chon_b', models.BooleanField(blank=True, null=True)),
                ('chon_c', models.BooleanField(blank=True, null=True)),
                ('chon_d', models.BooleanField(blank=True, null=True)),
                ('so_dien', models.CharField(blank=True, max_length=100)),
                ('dung', models.BooleanField(default=False)),
                ('diem_duoc', models.FloatField(default=0)),
                ('cau_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='de_thi.cauhoi')),
                ('ket_qua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tra_loi', to='de_thi.ketqua')),
            ],
        ),
    ]
