# Generated by Django 5.2.12 on 2026-04-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0002_dethi_creator_dethi_is_custom'),
        ('kien_thuc', '0001_initial'),
    ]

    operations = [
        # Xóa tất cả dữ liệu DeThi để tránh lỗi foreign key
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('de_thi', 'DeThi').objects.all().delete(),
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='dethi',
            name='mon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='de_thi', to='kien_thuc.mon'),
        ),
    ]
