# Generated by Django 5.2.12 on 2026-04-07 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0003_alter_dethi_mon'),
        ('kien_thuc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_lan_hoi', models.IntegerField(default=0)),
                ('so_lan_dung', models.IntegerField(default=0)),
                ('do_kho', models.FloatField(default=0.5)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('cau_hoi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='de_thi.cauhoi')),
            ],
            options={
                'verbose_name': 'Độ khó câu hỏi',
                'verbose_name_plural': 'Độ khó câu hỏi',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_bai_lam', models.IntegerField(default=0)),
                ('diem_trung_binh', models.FloatField(default=0)),
                ('tong_gio_lam', models.IntegerField(default=0)),
                ('dem_tien_tro', models.IntegerField(default=0)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân tích người dùng',
                'verbose_name_plural': 'Phân tích người dùng',
            },
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_bai_lam', models.IntegerField(default=0)),
                ('diem_trung_binh', models.FloatField(default=0)),
                ('so_dan_dung', models.IntegerField(default=0)),
                ('tong_dan_tra_loi', models.IntegerField(default=0)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kien_thuc.mon')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hiệu suất theo môn',
                'verbose_name_plural': 'Hiệu suất theo môn',
                'unique_together': {('nguoi_dung', 'mon')},
            },
        ),
    ]
