# Generated by Django 5.2.12 on 2026-04-07 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0004_questiondifficulty_useranalytics_subjectperformance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('vote_count', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('tac_gia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bình luận diễn đàn',
                'verbose_name_plural': 'Bình luận diễn đàn',
                'ordering': ['-vote_count', 'ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=300)),
                ('noi_dung', models.TextField()),
                ('is_solved', models.BooleanField(default=False)),
                ('vote_count', models.IntegerField(default=0)),
                ('so_binh_luan', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('best_answer_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_answer_for_post', to='de_thi.forumcomment')),
                ('cau_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='de_thi.cauhoi')),
                ('tac_gia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài diễn đàn',
                'verbose_name_plural': 'Bài diễn đàn',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='bai_dang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='de_thi.forumpost'),
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('vote_count', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('binh_luan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='de_thi.forumcomment')),
                ('tac_gia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trả lời bình luận',
                'verbose_name_plural': 'Trả lời bình luận',
                'ordering': ['ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_bau', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('bai_dang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='de_thi.forumpost')),
                ('binh_luan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='de_thi.forumcomment')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tra_loi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='de_thi.forumreply')),
            ],
            options={
                'verbose_name': 'Bầu chọn',
                'verbose_name_plural': 'Bầu chọn',
                'unique_together': {('nguoi_dung', 'bai_dang'), ('nguoi_dung', 'binh_luan'), ('nguoi_dung', 'tra_loi')},
            },
        ),
    ]
