# Generated by Django 5.2.12 on 2026-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0005_forumcomment_forumpost_forumcomment_bai_dang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketqua',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='is_violated',
            field=models.BooleanField(default=False),
        ),
    ]
