# Generated by Django 5.2.12 on 2026-04-08 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0006_ketqua_is_official_ketqua_is_violated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketqua',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ket_qua', to=settings.AUTH_USER_MODEL),
        ),
    ]
