# Generated by Django 5.2.12 on 2026-04-09 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0007_alter_ketqua_nguoi_dung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_hien_tai', models.IntegerField(default=0)),
                ('da_hoan_thanh', models.BooleanField(default=False)),
                ('ngay_bat_dau', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('de_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='de_thi.dethi')),
                ('ket_qua', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_session', to='de_thi.ketqua')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên luyện tập',
                'verbose_name_plural': 'Phiên luyện tập',
                'ordering': ['-ngay_bat_dau'],
            },
        ),
    ]
