# Generated by Django 5.2.12 on 2026-04-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0008_practicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketqua',
            name='danh_dau_khong_chinh_thuc',
            field=models.BooleanField(default=False),
        ),
    ]
