# Generated by Django 5.2.12 on 2026-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0009_ketqua_danh_dau_khong_chinh_thuc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cauhoi',
            options={'ordering': ['thu_tu'], 'verbose_name': 'Câu hỏi', 'verbose_name_plural': 'Câu hỏi'},
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='cau_hoi_images/', verbose_name='Hình ảnh minh họa'),
        ),
    ]
