# Generated by Django 5.2.13 on 2026-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0010_alter_cauhoi_options_cauhoi_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalytics',
            name='tong_bai_da_lam',
            field=models.IntegerField(default=0),
        ),
    ]
