# Generated by Django 5.2.13 on 2026-04-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0011_useranalytics_tong_bai_da_lam'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalytics',
            name='tong_gio_hoc',
            field=models.IntegerField(default=0),
        ),
    ]
