# Generated by Django 5.2.13 on 2026-04-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0012_useranalytics_tong_gio_hoc'),
    ]

    operations = [
    ]
