# Generated by Django 5.2.12 on 2026-04-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
            },
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('thu_tu', models.IntegerField(default=0)),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet', to='kien_thuc.mon')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['thu_tu', 'ngay_tao'],
            },
        ),
    ]
