# Generated by Django 5.2.12 on 2026-04-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('so_luong_the', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_flashcard_sets', to=settings.AUTH_USER_MODEL)),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='kien_thuc.mon')),
            ],
            options={
                'verbose_name': 'Bộ Flashcard',
                'verbose_name_plural': 'Bộ Flashcard',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_truoc', models.TextField(help_text='Câu hỏi / Khái niệm (hỗ trợ Markdown & MathJax)')),
                ('mat_sau', models.TextField(help_text='Câu trả lời / Giải thích (hỗ trợ Markdown & MathJax)')),
                ('thu_tu', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='kien_thuc.flashcardset')),
            ],
            options={
                'verbose_name': 'Thẻ Flashcard',
                'verbose_name_plural': 'Thẻ Flashcard',
                'ordering': ['thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_hoc', models.IntegerField(default=0)),
                ('lan_dung', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_hoc_truoc', models.DateTimeField(blank=True, null=True)),
                ('ngay_hoc_tiep', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('again', 'Lại (< 1 ngày)'), ('hard', 'Khó (3 ngày)'), ('good', 'Tốt (10 ngày)'), ('easy', 'Dễ (21 ngày)')], default='again', max_length=10)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kien_thuc.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiến độ Flashcard',
                'verbose_name_plural': 'Tiến độ Flashcard',
                'unique_together': {('user', 'flashcard')},
            },
        ),
    ]
