# Generated by Django 5.2.12 on 2026-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0002_flashcardset_flashcard_flashcardprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardprogress',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='flashcardprogress',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='flashcardprogress',
            name='lan_dung',
        ),
        migrations.RemoveField(
            model_name='flashcardprogress',
            name='lan_hoc',
        ),
        migrations.RemoveField(
            model_name='flashcardprogress',
            name='ngay_hoc_tiep',
        ),
        migrations.RemoveField(
            model_name='flashcardprogress',
            name='ngay_hoc_truoc',
        ),
        migrations.RemoveField(
            model_name='flashcardprogress',
            name='trang_thai',
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
