# Generated by Django 5.2.12 on 2026-04-08 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0004_tag_flashcardset_uuid_flashcardset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='next_review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='repetition_count',
            field=models.IntegerField(default=0),
        ),
    ]
