# Generated by Django 5.2.12 on 2026-04-08 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0005_flashcardprogress_ease_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardprogress',
            name='next_review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
