# Generated by Django 5.2.12 on 2026-04-08 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0006_alter_flashcardprogress_next_review_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='nguoi_dang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet', to=settings.AUTH_USER_MODEL),
        ),
    ]
