# Generated by Django 5.2.12 on 2026-04-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0007_baiviet_nguoi_dang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_bai_viet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='moderation_note',
            field=models.TextField(blank=True, help_text='Ghi chú kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('published', 'Đã xuất bản'), ('rejected', 'Bị từ chối')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_flashcard_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='moderation_note',
            field=models.TextField(blank=True, help_text='Ghi chú kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('published', 'Đã xuất bản'), ('rejected', 'Bị từ chối')], default='published', max_length=20),
        ),
    ]
