# Generated by Django 5.2.12 on 2026-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0008_baiviet_moderated_at_baiviet_moderated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('published', 'Đã xuất bản'), ('rejected', 'Bị từ chối')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('published', 'Đã xuất bản'), ('rejected', 'Bị từ chối')], default='pending', max_length=20),
        ),
    ]
