# Generated by Django 5.2.12 on 2026-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0010_add_draft_status_to_flashcard_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Số lượt xem bài viết'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='lan_xem',
            field=models.IntegerField(default=0, help_text='Số lượt xem bộ flashcard'),
        ),
    ]
