# Generated by Django 5.2.12 on 2026-04-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0012_flashcardtest_flashcardtestanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardtestanswer',
            name='bai_kiem_tra',
        ),
        migrations.RemoveField(
            model_name='flashcardtestanswer',
            name='flashcard',
        ),
        migrations.DeleteModel(
            name='FlashcardTest',
        ),
        migrations.DeleteModel(
            name='FlashcardTestAnswer',
        ),
    ]
