# Generated by Django 5.2.12 on 2026-04-11 08:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kien_thuc', '0013_remove_flashcardtestanswer_bai_kiem_tra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('tong_so_cau_hoi', models.IntegerField()),
                ('so_cau_tra_loi_dung', models.IntegerField(default=0)),
                ('diem', models.FloatField(default=0.0)),
                ('hoan_thanh', models.BooleanField(default=False)),
                ('thoi_gian_hoan_thanh', models.DateTimeField(blank=True, null=True)),
                ('bo_flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kien_thuc.flashcardset')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài kiểm tra Flashcard',
                'verbose_name_plural': 'Bài kiểm tra Flashcard',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cau_tra_loi', models.TextField()),
                ('dung', models.BooleanField()),
                ('thoi_gian_tra_loi', models.DateTimeField(auto_now_add=True)),
                ('thoi_gian_tra_loi_thuc_te', models.FloatField(blank=True, null=True)),
                ('bai_kiem_tra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_cau_tra_loi', to='kien_thuc.flashcardtest')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kien_thuc.flashcard')),
            ],
            options={
                'verbose_name': 'Câu trả lời kiểm tra Flashcard',
                'verbose_name_plural': 'Câu trả lời kiểm tra Flashcard',
                'unique_together': {('bai_kiem_tra', 'flashcard')},
            },
        ),
    ]