# Generated by Django 5.2.13 on 2026-04-13 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kien_thuc', '0014_flashcardtest_flashcardtestanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateTimeField(auto_now_add=True)),
                ('ngay_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_hoc', models.IntegerField(default=0)),
                ('so_the_da_xem', models.IntegerField(default=0)),
                ('so_the_da_hoc', models.IntegerField(default=0)),
                ('ty_le_dung', models.FloatField(default=0.0)),
                ('che_do', models.CharField(choices=[('study', 'Học mới'), ('review', 'Ôn tập'), ('test', 'Kiểm tra')], default='study', max_length=20)),
                ('bo_flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='kien_thuc.flashcardset')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên học Flashcard',
                'verbose_name_plural': 'Phiên học Flashcard',
                'ordering': ['-ngay_bat_dau'],
            },
        ),
    ]
