# Generated by Django 5.2.13 on 2026-04-14 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_thi', '0013_test_migration_dependency'),
        ('kien_thuc', '0016_merge_personal_knowledge_outline_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('question', 'Question'), ('flashcard', 'Flashcard'), ('article', 'Article')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Note content supporting Markdown and MathJax')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ghi chú cá nhân',
                'verbose_name_plural': 'Ghi chú cá nhân',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='notetag',
            name='unique_user_note_tag',
        ),
        migrations.AlterUniqueTogether(
            name='notetag',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='note',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='kien_thuc.baiviet'),
        ),
        migrations.AddField(
            model_name='note',
            name='flashcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='kien_thuc.flashcard'),
        ),
        migrations.AddField(
            model_name='note',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='de_thi.cauhoi'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'note_type'], name='kien_thuc_n_user_id_16466e_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='kien_thuc_n_user_id_f02faf_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_pinned', '-updated_at'], name='kien_thuc_n_user_id_8ffec0_idx'),
        ),
    ]
