# Generated by Django 5.2.12 on 2026-04-08 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_badge', models.BooleanField(default=True, verbose_name='Huy hiệu mới')),
                ('enable_forum_reply', models.BooleanField(default=True, verbose_name='Trả lời diễn đàn')),
                ('enable_leaderboard', models.BooleanField(default=True, verbose_name='Xếp hạng')),
                ('enable_achievement', models.BooleanField(default=True, verbose_name='Thành tựu')),
                ('enable_study_reminder', models.BooleanField(default=True, verbose_name='Nhắc nhở học tập')),
                ('enable_exam_result', models.BooleanField(default=True, verbose_name='Kết quả thi')),
                ('enable_flashcard_milestone', models.BooleanField(default=True, verbose_name='Cột mốc flashcard')),
                ('enable_system', models.BooleanField(default=True, verbose_name='Hệ thống')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Gửi email')),
                ('email_frequency', models.CharField(choices=[('instant', 'Ngay lập tức'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('never', 'Không bao giờ')], default='never', max_length=10, verbose_name='Tần suất email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Cài đặt thông báo',
                'verbose_name_plural': 'Cài đặt thông báo',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('badge', 'Huy hiệu mới'), ('forum_reply', 'Trả lời diễn đàn'), ('leaderboard', 'Xếp hạng'), ('achievement', 'Thành tựu'), ('study_reminder', 'Nhắc nhở học tập'), ('exam_result', 'Kết quả thi'), ('flashcard_milestone', 'Cột mốc flashcard'), ('system', 'Hệ thống')], max_length=20, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Link hành động')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Đã lưu trữ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đọc')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
